baseURL = 'https://elnyy.github.io/public'
locale = 'en-US'
title = 'test title'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v4"
