baseurl = "https://elnyy.github.io/"
title = "elnyy"
languageCode = "ja-jp"
paginate = "5" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Params.author]
  name = "elnyy"
  bio = "noun: a biography or biographical sketch"
  avatar = "img/avatar.png"

[Params]
  description = "" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false# Show "Read more" button in list if true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  googleFontsLink = "https://fonts.google.com/share?selection.family=Noto+Sans+JP:wght@100..900"

[Params.logo]
  subtitle = "たまにゲームを楽しみながら色々なツールに触れる" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = [ "search", "recent", "categories"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

# allow raw html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
